### ISSUE TITLE
UI: Input strings are converted to zero doubles

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_UI#193]
#### Description:

See the pic below:
![stringinput](https://user-images.githubusercontent.com/26874773/72158144-d98bb700-33b9-11ea-99d6-88c0a8ea4098.png)

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue193%2DInputStrings).

**Comment by adecler** [comment]
If someone desperately wants to use a string as an input for a point coordinate, who am I to stop them?

I had a quick look to see if there was anything on our code that was causing that but it seems to be on the Dynamo side. I am sure there is a way to ask Dynamo to throw a warning when that happen (as anything can always be casted to zero by default) but I don't see a near future where it becomes worth spending time on this.

I have assigned this to you in case you want to give it a go.

**Comment by pawelbaran** [comment]
@adecler to me it looks like it is rather on our end since native Dynamo component crash nicely on wrong input type:

![image](https://user-images.githubusercontent.com/26874773/72238985-c4906d00-35df-11ea-954b-d8424cb1de43.png)

Maybe there is some fallback on our end that forces the code to take default when the input type is incorrect?

I do not even know when to start tracing the bug, so I will unassign myself and leave the issue orphaned, maybe it will find someone to take care one day 🐒

**Comment by adecler** [comment]
@pawelbaran , this is true but this is a bit more complicated than that:
- Dynamo automatically transforms a method into a component in a very similar way to what we do with reflection. When it does, it uses the types of the method arguments to enforce what can and cannot be plugged into the inputs of the component.
- I our case, we are always asking Dynamo to use [RunCaller](https://github.com/BHoM/Dynamo_Toolkit/blob/master/Dynamo_Engine/Compute/RunCaller.cs) as the method to turn into a component (we just have to find the `RunCaller` method with the right number of arguments). Since this is a generic method, it only takes arguments of type `object`.
- This means we are loosing the enforcement on the input type. Unfortunately, Dynamo is not very flexible in term of the location of the method you can use for components so that was the only solution I could find. 
- There is potentially a way to force the types again but I honestly don't know how to do that. I say `potentially' because Dynamo is using a lot of private members and internal classes and has near to zero level of hackability. 

As you can see (i hope I was at least a bit clear), this input typing is deal with by Dynamo internally with no clear way for us to intervene. Things might be different in 2.1 but I am not holding my breath.

**Comment by FraserGreenroyd** [comment]
This will not be actioned as consensus is that this is a User-Error caused predominantly by Dynamo rather than anything we can easily support.
